### ISSUE TITLE
Office 365 ProPlus blocks the Enrollment Status Page

### ISSUE THREAD

**Issue by wadstromdev** [MicrosoftDocs/windows-itpro-docs#2220]
It appears that the Enrollment Status Page is now tracking Office 365 ProPlus installations. Even though the ProPlus installation succeeds, the Enrollment Status Page does not identify it as a successful installation and throws an error message when the Enrollment Status Page times out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5d94e38-75da-740c-d0cc-82bf27ba9c24
* Version Independent ID: 800a29d5-425c-7c32-b901-c425658ada81
* Content: [Windows Autopilot Enrollment Status page](https://docs.microsoft.com/en-us/windows/deployment/windows-autopilot/enrollment-status)
* Content Source: [windows/deployment/windows-autopilot/enrollment-status.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/enrollment-status.md)
* Product: **w10**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by afetscher** [comment]
observed the same behavior and thanks to your comment I could understand that it's Office. Do you already have new information?

**Comment by gallantrinity** [comment]
+1

**Comment by martin-rublik** [comment]
+1

**Comment by gallantrinity** [comment]
Looks like this was resolved with the latest Azure update yesterday. 

https://techcommunity.microsoft.com/t5/Intune-Customer-Success/Support-Tip-Office-C2R-installation-is-now-tracked-during-ESP/ba-p/295514

You can now select which apps to track. You can either remove office from the tracking or extend your timeout to allow office to finish installing.

**Comment by cloudtroll** [comment]
still doesn't work for me and others...see the comments in the article

https://techcommunity.microsoft.com/t5/Intune-Customer-Success/Support-Tip-Office-C2R-installation-is-now-tracked-during-ESP/ba-p/295514

**Comment by martin-rublik** [comment]
same with me

**Comment by wadstromdev** [comment]
Both the selective app tracking and OPP C2R seems to work on Windows 10 1809 for me, but neither is working on 1803.

**Comment by martin-rublik** [comment]
could be I tested on 1803, I'll check and come back later

**Comment by cloudtroll** [comment]
you are right, it only works on 1809

**Comment by gallantrinity** [comment]
I removed Office from tracking and it works fine for me on 1803. It would be nice to track Office without errors. Although, it finishes installing moments after getting to the profile with my SSD laptops. Not a deal breaker yet.

**Comment by gallan13** [comment]
That was short lived. Office is being tracked again even though I've removed it from tracking. I had to remove Office from our required apps so our Autopilot will succeed. Frustrating to say the least! Microsoft put the "Preview" name just so they can mess with us!

**Comment by jethrocne** [comment]
Any update on this working for Win v1803?

**Comment by xNiklasJern** [comment]
Has anyone else noticed strange behavior with the ESP?
I just now enrolled a 1809 computer, and right after entering the login credentials the ESP showed up, then all of sudden the choices for the user to choose if they want to use full diagnostic (and all the others) came, had to click through these to get back to the ESP

**Comment by mypil** [comment]
@officedocsbot assign @mypil

**Comment by mypil** [comment]
@wadstromdev - Thank you for submitting this feedback.

From our understanding, the document content has been updated by the author to incorporate the feedback/comments provided by the readers in this issue so we hope that the issue has been addressed. For your reference, kindly check on the following commits on the updates made by the author - [e7612c5 ](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/e7612c5c6a22e4a8242e78fcfefa33ee2f2b3376#diff-935dc67314389d276ba54a5b4521538d)/ [9728933](https://github.com/MicrosoftDocs/windows-itpro-docs/commit/9728933e58751fac61c25b625eeb8ad6c8760c60#diff-935dc67314389d276ba54a5b4521538d).  If you feel it hasn't been resolved, please re-open this issue.


Thank you for your contribution to make the docs better! Much appreciated!

**Comment by mypil** [comment]
@officedocsbot close
