### ISSUE TITLE
Windows Hello certificates requires enabling a permitted strong authentication provider

### ISSUE THREAD

**Issue by scout249** [MicrosoftDocs/windows-itpro-docs#3225]
When I run the command to enroll for an enrollment agent certificate, I got the following error.

Set-AdfsCertificateAuthority -EnrollmentAgent -EnrollmentAgentCertificateTemplate WHFBEnrollmentAgent -WindowsHelloCertificateTemplate WHFBAuthentication

WARNING: PS0343: Issuing Windows Hello certificates requires enabling a permitted strong authentication provider, but no usable providers are
currently configured.  These authentication providers are not supported for Windows Hello certificates: MicrosoftPassportAuthentication.
Windows Hello certificates will not be issued until a permitted strong authentication provider is configured.
<pre>
PS C:\> Get-AdfsAuthenticationProvider | ft

AdminName                         AllowedForPrimaryExtranet AllowedForPrimaryIntranet AllowedForAdditionalAuthentication AuthenticationMethods
---------                         ------------------------- ------------------------- ---------------------------------- ---------------------
Forms Authentication                                   True                      True                              False {urn:oasis:names:t...
Windows Authentication                                False                      True                              False {urn:ietf:rfc:1510...
Certificate Authentication                             True                      True                               True {urn:ietf:rfc:2246...
Device Authentication                                  True                      True                              False {http://schemas.mi...
Azure MFA                                              True                      True                              False {http://schemas.mi...
Azure MFA                                             False                     False                               True {http://schemas.mi...
Microsoft Passport Authentication                      True                      True                              False {urn:ietf:rfc:2246...
</pre>

**Comment by mypil** [comment]
@scout249 - Thank you for submitting feedback.

I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. Based on outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  **https://docs.microsoft.com/office365/admin/contact-support-for-business-products**

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by mypil** [comment]
@officedocsbot close

**Comment by kylecweeks** [comment]
I understand that this is closed. Seeing as there was no update - adding in that I deployed a Server 2019 Server by mistake and received this exact same error. Server 2016 ADFS did not.

**Comment by AaronMountford** [comment]
Another note to say that I also received this exact error on Server 2019, despite the Authentication Providers being set the same as the original post.    Hybrid Certificate based WHFB works in spite of the error with ADFS on Server 2019.    I would consider this a bug in the Set-AdfsCertificateAuthority cmdlet.

**Comment by illfated** [comment]
To those of you who still experience this issue; if you find that this is something that could be resolved or improved upon in the documentation on docs.microsoft.com, please open a new ticket from the related page to make it easier for contributors to see what needs to be done.

Thanks in advance.

**Comment by kklouzal** [comment]
I too experienced this exact same thing today while setting up an On-Prem Certificate based WHFB environment. Despite the message outlined in the OP, WHFB appears to be functioning properly..

**Comment by jbostoen** [comment]
WHFB gets activated, but mind to enable Multi Factor authentication in ADFS > Authentication Methods.
