### ISSUE TITLE
[LOC] "_gt" needs to be replaced with ">"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#3405]
https://docs.microsoft.com/ja-jp/windows/security/threat-protection/intelligence/unwanted-software

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 8f28f994-ad0f-72e5-79d2-6898421cb2fd
* Version Independent ID: dbb83bbb-73cc-8233-15fb-1363b8ad1cd1
* Content: [Autopilot デバイスの BitLocker 暗号化アルゴリズムの設定](https://docs.microsoft.com/ja-jp/windows/deployment/windows-autopilot/bitlocker)
* Content Source: [windows/deployment/windows-autopilot/bitlocker.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/windows/deployment/windows-autopilot/bitlocker.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @greg-lindsay
* Microsoft Alias: **greg-lindsay**

**Comment by mypil** [comment]
@officedocsbot assign @mypil
@officedocsbot assign @dongmicro
@officedocsbot add label localization

**Comment by mypil** [comment]
@dongmicro - Can you please assist with this Translation (Localization) issue?

**Comment by illfated** [comment]
Maybe it would be better to use the HTML code `&#62;` instead of the actual `>` character?
It does work to produce a visible Greater Than ( &#62; ) symbol, as used in the Github text.
(Then again, I don't know if this needs to be worked on in some automated process.)

**Comment by e0i** [comment]
Similar: #3460 #3413 #3412 #3406 #3448 #3454

**Comment by illfated** [comment]
Looking back at the originating document to see where the unwanted "_gt" character combination stems from, it looks like the "arrow marker" `->` (hyphen + Greater Than) is the originating character combination:
> The settings are available under Device Configuration -> Profiles -> Create profile -> Platform = Windows 10 and later, Profile type = Endpoint protection -> Configure -> Windows Encryption -> BitLocker base settings, Configure encryption methods = Enable.
>
> Note: It is also recommended to set Windows Encryption -> Windows Settings -> Encrypt = **Require**.

`The settings are available under Device Configuration -> Profiles -> Create profile -> Platform = Windows 10 and later, Profile type = Endpoint protection -> Configure -> Windows Encryption -> BitLocker base settings, Configure encryption methods = Enable.`

`Note: It is also recommended to set Windows Encryption -> Windows Settings -> Encrypt = **Require**.`

Given the amount of pages where this issue seems to happen a lot, and because I don't know anything at all about the translation process to create the Japanese pages, I can only share my thoughts on theoretical alternatives. I wonder what is more efficient and practical, waiting for a solution to be worked out in the translation process, or modify the original English pages with a different character combination or symbol to represent an arrow between the steps in the text (maybe only the Greater Than character, to remove the hyphen). I wonder if there is any other useful character with a similar arrow-like look, but would not be within the translatable character set, as a workaround to preserve the arrow-like similarity.

**Comment by e0i** [comment]
See variant: #3819

**Comment by mypil** [comment]
@officedocsbot unassign @mypil

**Comment by illfated** [comment]
@hyoshioka0128 : Please confirm that the problem has been solved on
https://docs.microsoft.com/ja-jp/windows/deployment/windows-autopilot/bitlocker

**Comment by hyoshioka0128** [comment]
@illfated Thank you. (I'm poor English)
Many of the problems linked above seem to be resolved.
I will check it.

However, I did not have isuue left.
Search word(Bing and Google): "gt" ;docs.microsoft.com/ja-jp/windows/"
 「時刻 (Windows 10) | Microsoft Docs」
  "https://docs.microsoft.com/ja-jp/windows/configuration/wcd/wcd-time"
![wcd-time](https://user-images.githubusercontent.com/40815708/59155439-b4059a80-8ac4-11e9-97d1-476ad2f4c685.png)

I already created a problem report for "Windows-insiders".
 "https://github.com/MicrosoftDocs/windows-insider/issues/123"

**Comment by hyoshioka0128** [comment]
@illfated : #3580 was not fixed (Search word "_gt" ;docs.microsoft.com/ja-jp/windows/")

**Comment by hyoshioka0128** [comment]
@illfated : #3490  "_gt" is fixed but ">>"
![windows-update-troubleshooting_j](https://user-images.githubusercontent.com/40815708/59160053-9b20d780-8b0c-11e9-80b4-381893cba709.png)

**Comment by e0i** [comment]
@hyoshioka0128 @illfated 

It has been officially confirmed that the group of related issues referenced to this issue have been fixed.

Thank you for your valuable feedback and contributions.

**Comment by e0i** [comment]
@officedocsbot close

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@officedocsbot close
