### ISSUE TITLE
[LOC] "件" needs to be replaced with "1"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#3902]
related issues:#3891
![adobe-settings-gp_j1](https://user-images.githubusercontent.com/40815708/58848424-8504b880-86c1-11e9-85ea-24cc650b7f34.png)

![adobe-settings-gp_j2](https://user-images.githubusercontent.com/40815708/58848428-8afa9980-86c1-11e9-97a8-f5c64760b375.png)

https://docs.microsoft.com/ja-jp/microsoft-edge/deploy/group-policies/adobe-settings-gp

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 0a7fe2c9-aae2-5095-fe96-9699de018300
* Version Independent ID: cfc2c4e1-dd70-0e39-4d39-beb5c8ca270b
* Content: [Microsoft Edge-Adobe Flash グループポリシー](https://docs.microsoft.com/ja-jp/microsoft-edge/deploy/group-policies/adobe-settings-gp)
* Content Source: [browsers/edge/group-policies/adobe-settings-gp.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/edge/group-policies/adobe-settings-gp.md)
* Product: **edge**
* Technology: **microsoft-edge**
* GitHub Login: @eavena
* Microsoft Alias: **eravena**

**Comment by illfated** [comment]
Probably a Machine Translation issue, although not sure if the mix of English/kanji in the preceding column could have anything to do with it. Maybe @dongmicro could take a look and comment on it.

**Comment by e0i** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@officedocsbot assign @dongmicro
@officedocsbot add label localization

**Comment by e0i** [comment]
See: #3930

**Comment by dongmicro** [comment]
Hello,

The project, itpro-docs were transferred to Tina.

Thanks,
Dong

发件人: Onur <notifications@github.com>
发送时间: 2019年6月19日 7:19
收件人: MicrosoftDocs/windows-itpro-docs <windows-itpro-docs@noreply.github.com>
抄送: Dong Wang (OSG_LOC) <dongwa@microsoft.com>; Assign <assign@noreply.github.com>
主题: Re: [MicrosoftDocs/windows-itpro-docs] [LOC] "件" needs to be replaced with "1" (#3902)


See: #3930<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fwindows-itpro-docs%2Fissues%2F3930&data=02%7C01%7Cdongwa%40microsoft.com%7C4e29b5d3be1c4ae1b0c508d6f4c1085d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636965507238038819&sdata=6URxiEhZE3m7l9u02Tv0bPcUUzGBbPykFeyvVv6ms0s%3D&reserved=0>

**Comment by illfated** [comment]
OK, so I checked the list for MicrosoftDocs (https://github.com/orgs/MicrosoftDocs/people -- 619 members), but no match there. The main Microsoft member list, https://github.com/orgs/microsoft/people -- 4254 members) seems to contain a likely match, https://github.com/xuachen -- is that the correct Tina?

**Comment by e0i** [comment]
@officedocsbot assign @MollyMalone

**Comment by e0i** [comment]
@officedocsbot unassign @MollyMalone
@officedocsbot unassign @TinaMcN

**Comment by e0i** [comment]
@officedocsbot unassign @dongmicro

**Comment by TinaMcN** [comment]
@hyoshioka0128 フィードバックをありがとうございました。 これは MT ツールの問題です。 私はツールの所有者に問題を報告しました。  この問題がすぐに解決されるとは思いません。 修正が必要になったときに更新します。(Thank you for the feedback.  This is a problem with the MT tool.  I have reported the problem to the tool owners.   I don't expect this issue to be fixed quickly.  I will update when we have a fix.)

**Comment by TinaMcN** [comment]
フィードバックをありがとうございました。 記事は機械翻訳されました。 私は人間の翻訳のためにそれを送った。 翻訳が完了するまでに最大4週間かかります。 (Thank you for the feedback.  The article was machine translated.  I sent it for human translation.  It will take up to 4 weeks to complete the translation.)

**Comment by TinaMcN** [comment]
フィードバックをありがとうございました。 記事は機械翻訳されました。 私は人間の翻訳のためにそれを送った。 翻訳が完了するまでに最大4週間かかります。 (Thank you for the feedback.  The article was machine translated.  I sent it for human translation.  It will take up to 4 weeks to complete the translation.)

**Comment by hyoshioka0128** [comment]
@TinaMcN - Not Corrected.
![adobe-settings-gp_1](https://user-images.githubusercontent.com/40815708/71782247-7269ad80-301b-11ea-9e6c-7fc939ca52c0.png)

![adobe-settings-gp_2](https://user-images.githubusercontent.com/40815708/71782250-7695cb00-301b-11ea-9c26-9d48e29ff5a2.png)

**Comment by illfated** [comment]
@hyoshioka0128 : I don't see any message from TinaMcN saying that this issue is solved yet.
Need to wait 10 days or more, according to the estimated 4 weeks to complete the translation.

**Comment by hyoshioka0128** [comment]
@illfated  - Thank you for pointing out.
@TinaMcN - I misunderstood. Wait for translation.

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間が翻訳されています。 修正済みであることを確認してください。 フィードバックのおかげで再び (The article is now human translated. Please verify that it is fixed. Thanks again for the feedback)

**Comment by illfated** [comment]
Sorry, but the original issue still persists. I don't know Japanese or kanji enough to tell why they think that **件** is a valid replacement for 1, but the article should never imply that 件 can be used as a software value inside the application table. The preceding lines show the value 0 (zero), so it should be rather obvious that this may be a binary value (or boolean), using 0 or 1 as the values for "on" or "off".

**Comment by hyoshioka0128** [comment]
@TinaMcN - Not Corrected.
Thanks.

**Comment by TinaMcN** [comment]
@hyoshioka0128 そのことについてお詫び申し上げます。  私は翻訳者に問題を調査し、修正するように頼みました。 (I apologise about that.   I have asked the translators to investigate and fix the issue.)

**Comment by TinaMcN** [comment]
@hyoshioka0128 この問題は最終的に修正されました。  私たちはそれを修正する方法を考え出したようにあなたの忍耐をありがとう。  (This issue is finally fixed.   Thank you for your patience as we figured out how to fix it.)

**Comment by illfated** [comment]
Looks good now, thank you for the effort with this issue.

**Comment by hyoshioka0128** [comment]
@TinaMcN - Fixed.
Closed #3902.
Thanks.
