### ISSUE TITLE
[LOC] "両面" needs to be replaced with "2"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/windows-itpro-docs#4039]
related issue: #3930

ja-jp:https://docs.microsoft.com/ja-jp/microsoft-edge/deploy/available-policies
![available-policies_j](https://user-images.githubusercontent.com/40815708/59548999-c9316c00-8f91-11e9-9930-c642d73a26a5.png)

"件" needs to be replaced with "1"
"両面" needs to be replaced with "2"

en-us:https://docs.microsoft.com/en-us/microsoft-edge/deploy/available-policies
![available-policies_e](https://user-images.githubusercontent.com/40815708/59549001-d0f11080-8f91-11e9-9060-8411b12a85f0.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 9aa5c0a6-acd2-4ec3-275d-3a684b3faaf4
* Version Independent ID: 6b475925-ca66-d47f-e180-92988683b37a
* Content: [Microsoft Edge のグループ ポリシーとモバイル デバイス管理の設定 (IT 担当者向けの Microsoft Edge)](https://docs.microsoft.com/ja-jp/microsoft-edge/deploy/available-policies)
* Content Source: [browsers/edge/available-policies.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/master/browsers/edge/available-policies.md)
* Product: **edge**
* Technology: **microsoft-edge**
* GitHub Login: @eavena
* Microsoft Alias: **eravena**

**Comment by jvsam** [comment]
@officedocsbot assign @e0i

**Comment by e0i** [comment]
@officedocsbot assign @dongmicro
@officedocsbot add label localization

**Comment by e0i** [comment]
@officedocsbot assign @MollyMalone

**Comment by e0i** [comment]
@officedocsbot unassign @MollyMalone
@officedocsbot unassign @TinaMcN

**Comment by e0i** [comment]
@officedocsbot unassign @dongmicro

**Comment by TinaMcN** [comment]
@hyoshioka0128 フィードバックをありがとうございました。 これは MT ツールの問題です。 私はツールの所有者に問題を報告しました。 この問題がすぐに解決されるとは思いません。 修正が必要になったときに更新します。(Thank you for the feedback. This is a problem with the MT tool. I have reported the problem to the tool owners. I don't expect this issue to be fixed quickly. I will update when we have a fix.)

**Comment by TinaMcN** [comment]
フィードバックをありがとうございました。 記事は機械翻訳されました。 私は人間の翻訳のためにそれを送った。 翻訳が完了するまでに最大4週間かかります。 (Thank you for the feedback.  The article was machine translated.  I sent it for human translation.  It will take up to 4 weeks to complete the translation.)

**Comment by TinaMcN** [comment]
@hyoshioka0128 記事は現在、人間が翻訳されています。 修正済みであることを確認してください。 フィードバックのおかげで再び (The article is now human translated. Please verify that it is fixed. Thanks again for the feedback)

**Comment by illfated** [comment]
Unfortunately, the issue does not appear to be resolved yet. (is the solution delayed?)

"件" needs to be replaced with the number value 1 -- (_48 pairs of_ 件 _in the tables on this page, 96 entries in total_)

"両面" needs to be replaced with the number value 2 -- (_7 pairs of_ 両面 _in the tables on this page, 14 entries in total_)

**Comment by hyoshioka0128** [comment]
@TinaMcN - Not Corrected.
Thanks.

**Comment by TinaMcN** [comment]
そのことについてお詫び申し上げます。  私は翻訳者に問題を調査し、修正するように頼みました。 (I apologise about that.   I have asked the translators to investigate and fix the issue.)

**Comment by TinaMcN** [comment]
@illfated thanks for the helpful summary!

**Comment by denisebmsft** [comment]
I believe this issue is now resolved. Thank you @hyoshioka0128 for reporting this and @TinaMcN for the excellent follow up.

**Comment by illfated** [comment]
@denisebmsft : That depends on how you define "this issue is now resolved" -- if it means that a decision to resolve the problem has been reached and that the implementation of that decision will be carried out in the future, then I agree. Just note that at the date & time of writing (2020-02-26 02:22 GMT), the incorrect page content itself has not yet been corrected.

**Comment by TinaMcN** [comment]
This issue is unfortunately not yet fixed.  We should reopen it.   The localization vendor was investigating it but got stuck trying to troubleshoot it.  We just switched to a new localization vendor and I've asked them to investigate it.  Hopefully will have some news in a few days.

**Comment by illfated** [comment]
(Ref. issue ticket #6127 )

**Comment by TinaMcN** [comment]
@hyoshioka0128 この問題は最終的に修正されました。 私たちはそれを修正する方法を考え出したようにあなたの忍耐をありがとう。 (This issue is finally fixed. Thank you for your patience as we figured out how to fix it.)

**Comment by illfated** [comment]
Confirmed. All the tables are now showing the values 0, 1, 2, 3 where needed.

**Comment by hyoshioka0128** [comment]
@TinaMcN - Fixed.
Closed #4039.
Thanks.
