### ISSUE TITLE
Fix does not work.

### ISSUE THREAD

**Issue by jimdgit** [MicrosoftDocs/windows-itpro-docs#8664]
[Enter feedback here]

Does not work to fix the issue.
The parameter -Sdll is invalid. in the PS command.
The suggested fix does not properly fix the security issue,
Does not work in PS:
sc sdset bdesvc D:(A;;CCDCLCSWRPWPDTLORCWDWO;;;SY)(A;;CCDCLCSWRPWPDTLORCWDWO;;;BA)(A;;CCLCSWRPLORC;;;BU)(A;;CCLCSWRPLORC;;;AU)S:(AU;FA;CCDCLCSWRPWPDTLOSDRCWDWO;;;WD)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31baa23e-2ca3-617f-c061-cfbcff4909ce
* Version Independent ID: fa64d25d-48ef-8c20-7227-ea78b6294bf4
* Content: [BitLocker cannot encrypt a drive  known issues - Microsoft 365 Security](https://docs.microsoft.com/en-us/windows/security/information-protection/bitlocker/ts-bitlocker-cannot-encrypt-issues)
* Content Source: [windows/security/information-protection/bitlocker/ts-bitlocker-cannot-encrypt-issues.md](https://github.com/MicrosoftDocs/windows-itpro-docs/blob/public/windows/security/information-protection/bitlocker/ts-bitlocker-cannot-encrypt-issues.md)
* Product: **w10**
* Technology: **windows**
* GitHub Login: @Teresa-Motiv
* Microsoft Alias: **v-tea**

**Comment by illfated** [comment]
Hmm. 2 possible issues at play here:

1. I am trying to locate the parameter `-Sdll` (as you typed it), but I can only find `-Sddl` in the 2 images. Not sure how to test this, because I don't have any easy access to a system to test this on (I don't think Windows 10 Home or Pro are enough for precise testing). Could you confirm if this issue also appears if you use the parameter **`-Sddl`** instead?

2. **SC** — without its extension part of the command file name — should only be used in a CMD window, not in PowerShell. **PowerShell** interprets "SC" as shorthand for `Set-Content` instead of SC.exe — hence it is the necessary to use the full command `SC.exe` in PowerShell.

Please test again while using `SC.exe` in PowerShell, as well as double-checking that the parameter **`-Sddl`** is typed correctly.

I do want to start a Pull Request to have the example command corrected to SC.exe and the syntax highlighting corrected to "PowerShell", but that may have to wait until the coming weekend.

**Comment by VLG17** [comment]
@jimdgit As @illfated very well pointed out, please make sure you use the correct parameter which is -Sddl (Security Descriptor Definition Language).

@illfated regarding the second point, the command should be run in Powershell and it works, according to my testing.

@jimdgit Do you get an error when running it in Powershell, or what do you mean with it doesn't work?

**Comment by jimdgit** [comment]
Yes power shell did not run it but I am not a ps expert.
It did run in cmd.

**Comment by jimdgit** [comment]
BTW this is the first time in decades any of my feedback did anything
Thanks for helping.

**Comment by illfated** [comment]
@jimdgit : Thank you for your practical feedback. Would you say that your issue is resolved now, or do you still find that there is an obvious need for document improvement for your case?

**Comment by jimdgit** [comment]
Well it's better but it did not solve my bitlocker issue.
Thanks

**Comment by illfated** [comment]
I may be a bit slow to notice how it looks from your perspective. Could you share some more details about the remaining issues you are seeing? Have you tried using `Sc.exe` as the main command in PowerShell, just in case your PowerShell environment uses the macro `@SC = Set-Content;` ?

**Comment by jimdgit** [comment]
The real problem is this, which before a recent update did not happen. This
is on a flash drive:
When you try to turn on bitlocker:
[image: image.png]

**Comment by jimdgit** [comment]
Also why on why would you make this an image that you can not copy from (as
noted -Sdll should be-sdll):
[image: image.png]

**Comment by jimdgit** [comment]
This command is broken when you copy and paste it:
[image: image.png]

**Comment by illfated** [comment]
Please note: it is usually not possible to send images to GitHub tickets via email. You need to post them on the web page directly.

**Comment by jimdgit** [comment]
Really this is what I need to fix and I did get the DACL to where it should be but still:
![image](https://user-images.githubusercontent.com/7762907/100278611-2d03e680-2f33-11eb-8e16-4a930d2e65a4.png)

**Comment by illfated** [comment]
Thank you for the details. Wish I knew this tech better, but I defer to the other users and MS Docs members for more information about this.

@RAJU2529 : Do you know something useful in this context, or where we should look for the causes in this issue?

**Comment by RAJU2529** [comment]
@illfated . Before giving instructions , I must view all commands as he tried in powershell with screenshot and by recorded video. 
 also from my basic knowledge, bitlocker does not enable for USB pendrive. 
 Bitlocker works with USB SSD with proper compatible convertor.  M.2 SSD have windows 10 OS is installed already , so it can be enable bitlocker
here is the proof.

**Comment by RAJU2529** [comment]
@jimdgit , send the screenshots indicating entered commands. or  record a video and upload to cloudstorage and share the link here

**Comment by RAJU2529** [comment]
@jimdgit . try below solution , open powershell  with adminrights  and type the following and press enter

**cd C:**

![Capture1](https://user-images.githubusercontent.com/3296790/100346156-660e8a80-3009-11eb-8484-43dafe9ea0da.JPG)

ConvertFrom-SddlString -Sddl "D:(A;;CCDCLCSWRPWPDTLORCWDWO;;;SY)(A;;CCDCLCSWRPWPDTLORCWDWO;;;BA)(A;;CCLCSWRPLORC;;;BU)(A;;CCLCSWRPLORC;;;AU)S:(AU;FA;CCDCLCSWRPWPDTLOSDRCWDWO;;;WD)" -Type ActiveDirectoryRights

![Capture2](https://user-images.githubusercontent.com/3296790/100346290-99511980-3009-11eb-95a0-1825ad3acc67.JPG)

then set the Bitlocker Drive Encryption Services  to automatic and start the service  by using   service.msc 
and restart the service.

**Comment by illfated** [comment]
@RAJU2529 : Thank you very much for the detailed feedback and information. That looks very useful to me, so I hope it looks useful to @jimdgit as well.

@jimdgit : Have you considered the fact that BitLocker only works on proper drives with HDD or SSD characteristics? There is also a lower limit to how small the drive can be before BitLocker refuses to access the drive. Myself, I would not test BitLocker with less than 64 GB or 128 GB drive size before I would consider something else as the cause for BitLocker to be faulty on my equipment.

**Comment by jimdgit** [comment]
"the fact that BitLocker only works on proper drives with HDD or SSD characteristics?" 100% Wrong I have used on flash drives often. Ok I get it your a bunch of noobs you are not willing to even do proper research.
Bye.

**Comment by VLG17** [comment]
> Really this is what I need to fix and I did get the DACL to where it should be but still:
> 
> Note this is a flash drive, that bitlocker used to work on until an update:
> 
> ![image](https://user-images.githubusercontent.com/7762907/100278611-2d03e680-2f33-11eb-8e16-4a930d2e65a4.png)

@jimdgit Are you connecting remotely to the machine where you have your flash drive that you want to encrypt or are you logged in locally. I see this issue happens when connecting over RDP, more details [here](https://social.technet.microsoft.com/Forums/en-US/575fa1b9-809a-43ac-9d4c-d11b6cf8badb/unable-to-encrypt-removable-usb-drive-quotaccess-deniedquot?forum=mdopmbam).

Since you are dealing with a technical issue, my suggestion is to [reach out to support](https://support.microsoft.com/contactus) or leverage [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/search.html?c=&includeChildren=&f=&type=question+OR+idea+OR+kbentry+OR+answer+OR+topic+OR+user&redirect=search%2Fsearch&sort=relevance&q=bitlocker). If the conclusion is that we need to add something to the documentation, we will do that.

**Comment by RAJU2529** [comment]
@VLG17 . Yea some note points should be added in document, 
list of possible reasons where the bitlocker encryption gets failed.

**Comment by jimdgit** [comment]
Yes! That was it I was on RDP. Well this is not a good feature as some of my PCs are headless - a real bug that should be fixed but thank you so much for the solution!
